# This is a basic workflow to help you get started with Actions

name: github-project-issue-to-sheets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
 workflow_dispatch:
 issues:
   types: [opened, deleted, transferred, closed, reopened, assigned, unassigned, labeled, unlabeled]
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 github-project-issue-sorter:
    runs-on: ubuntu-latest
    name: github-project-issue-to-sheets
    steps:
    - name: github-project-issue-to-sheets
      id: github-project-issue-to-sheets
      uses: ViRGiL175/github-project-issue-to-sheets@dev
      with:
       google-api-service-account-credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_DATA }}
       document-id: '1b0UuGS_HXTGv-Bc9LcB_58gZvo5fttyKgle0s4DmRNI'
       sheet-name: 'GitHub Issues'
